# .prettierrc.toml
"$schema" = "https://json.schemastore.org/prettierrc"
printWidth = 120
tabWidth = 2
useTabs = true
semi = true
singleQuote = true
quoteProps = "consistent"
jsxSingleQuote = false
trailingComma = "es5"
bracketSpacing = true
bracketSameLine = false
arrowParens = "always"
proseWrap = "preserve"
vueIndentScriptAndStyle = true
endOfLine = "lf"
singleAttributePerLine = true
